version: "3.5"

volumes:
  postgres_main:
    external: true
    
networks:
  losst-network:  
  
services:
  
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports:
      - ${HTTP_PORT-80}:80
      - ${HTTPS_PORT-443}:443
    links:
      - php
    networks:
      - losst-network
  
  database:
    ports:  #Нельзя использовать проброс портов на реальном проекте
      - "127.0.0.1:5432:5432"
    image: postgres:alpine
    volumes:
      - postgres_main:/var/lib/postgresql/data:delegated
    environment:
      - "POSTGRES_USER=pguser"
      - "POSTGRES_PASSWORD=pguser"
      - "POSTGRES_DB=main-db"
    networks:
      - losst-network
      
  php:
    build:
      context: ./docker/php-fpm
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/var/www
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - database
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - losst-network
  
  encore:
    image: node:alpine
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/app
      - ${HOME}/.yarn:/.yarn
      - ${HOME}/.yarnrc:/.yarnrc
      - ${HOME}/.cache/yarn:/.cache/yarn
    working_dir: /app
